# Backend
backend = "glx";

# VSync
vsync = true;

# Shadows
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;

# Opacity
inactive-opacity = 0.9;
active-opacity = 0.9;
frame-opacity = 0.7;
inactive-opacity-override = true;
blur-background = true;

# Fading
fading = true;
fade-delta = 4;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Blur
blur-method = "dual_kawase";
blur-strength = 8;

# Other
detect-client-opacity = true;
corner-radius = 15;

