# A majority of this configures the peacock server emulator, which bypasses the official ioi servers and basically makes the game better.
{inputs, ...}: {
  flake.nixosModules.desktop_steam = {
    config,
    pkgs,
    lib,
    ...
  }: let
    backup = config.custom.backup;
    hmConfig = config.home-manager.users.dastarruer;

    steamPath = "${hmConfig.home.homeDirectory}/.local/share/Steam/steamapps";
    hitmanPath = ''${hmConfig.home.homeDirectory}/.local/share/Steam/steamapps/common/HITMAN 3'';

    iniFormat = pkgs.formats.ini {};
    smfPrefix = "3086416570";

    activationScript = pkgs.writeShellApplication {
      name = "remove_hitman_mods";
      runtimeInputs = [pkgs.coreutils];
      text = ''
        rm -rf "${hitmanPath}/Simple Mod Framework"
        rm -rf "${hitmanPath}/Retail/mods"
        rm -rf "${hitmanPath}/Retail/licenses"
        rm -r "${hitmanPath}/Retail/crashpad_handler.exe"
        rm -r "${hitmanPath}/Retail/dinput8.dll"
        rm -r "${hitmanPath}/Retail/LICENSE"
        rm -r "${hitmanPath}/Retail/ResourceLib_HM3.dll"
        rm -r "${hitmanPath}/Retail/ZHMModSDK.dll"
      '';
    };

    # This is the path to the json file generated by smf after deploying mods. Since linux is so special and cool, mission companion cannot find this file in the place it usually is, so we have to manually set the path.
    # Also note the \ instead of / for paths because windows
    lastDeployJsonPath = ''Z:\home\dastarruer\.local\share\Steam\steamapps\compatdata\${smfPrefix}\pfx\drive_c\users\steamuser\Local Settings\Application Data\Simple Mod Framework\lastDeploy.json'';

    peacockDir = "${hmConfig.home.homeDirectory}/.config/peacock-linux";
    peacockPkg = pkgs.fetchzip {
      url = "https://github.com/thepeacockproject/Peacock/releases/download/v8.9.0/Peacock-v8.9.0-linux.zip";
      hash = "sha256-Lxo3UwqLyCsvD35ZmUTedkLBkg5iJnghezBn7FsBURQ=";
    };
    port = 3000;
    peacockScript = pkgs.writeShellApplication {
      name = "peacock-setup";
      runtimeInputs = with pkgs; [
        nodejs_24
        coreutils
        gnugrep
      ];
      text = ''
        BOLD='\e[1m'
        RESET='\e[0m'
        RED='\e[31m'
        GREEN='\e[32m'
        BLUE='\e[34m'

        success_message() { echo -e "[''${GREEN}''${BOLD}✔''${RESET}] $1!"; }
        error_message() { echo -e "[''${RED}''${BOLD}Error''${RESET}] $1"; }
        info_message() { echo -e "\n[''${BLUE}''${BOLD}Info''${RESET}] $1"; }

        mkdir -p "${peacockDir}"
        cd "${peacockDir}"

        # Userdata lives OUTSIDE the versioned Peacock/ dir so it survives reinstalls
        mkdir -p userdata

        INSTALLED_VERSION=""
        [ -f "./Peacock/.nix-version" ] && INSTALLED_VERSION=$(cat "./Peacock/.nix-version")

        if [ "''${INSTALLED_VERSION}" != "${peacockPkg}" ]; then
            rm -rf ./Peacock
            cp -r --no-preserve=mode "${peacockPkg}" ./Peacock
            rm -rf ./Peacock/userdata
            ln -s ../userdata ./Peacock/userdata
            echo "${peacockPkg}" > ./Peacock/.nix-version
        fi

        # Copy patcher files to Steam
        STEAM_DIR="''${HOME}/.local/share/Steam"
        VDF_FILE="''${STEAM_DIR}/steamapps/libraryfolders.vdf"

        if [ -f "''${VDF_FILE}" ]; then
            STEAM_PATHS=$(grep -oP '"path"\s+"\K[^"]+' "''${VDF_FILE}")
            HITMAN_FOUND=false

            for i in ''${STEAM_PATHS}; do
                TARGET_DIR="''${i}/steamapps/common/HITMAN 3"
                if [ -d "''${TARGET_DIR}" ]; then
                    HITMAN_FOUND=true
                    info_message "Found Hitman 3 in ''${TARGET_DIR}"

                    if cp Peacock/PeacockPatcher.exe "''${TARGET_DIR}/" && \
                       cp "${inputs.peacock}/legacy/WineLaunch.bat" "''${TARGET_DIR}/"; then
                        success_message "Copied Patcher and WineLaunch.bat successfully!"
                    else
                        error_message "Failed to copy Patcher or WineLaunch.bat (Check if WineLaunch.bat exists in ${peacockDir})"
                    fi
                fi
            done

            if [ "''${HITMAN_FOUND}" = false ]; then
               error_message "Hitman 3 folder not found in Steam libraries."
            fi
        fi

        # START THE SERVER
        if [ -f "Peacock/chunk0.js" ]; then
            info_message "Starting Peacock Server..."
            cd Peacock
            PORT=${toString port} exec node chunk0.js
        fi
      '';
    };
  in {
    # for now do this to replace files on every rebuild until steam-config-nix supports it
    system.activationScripts.preActivation.text = "${lib.getExe activationScript}";

    programs.steam.config = {
      # hitman
      apps."1659040" = {
        compatTool = "proton_11"; # having performance issues w latest ge proton
        systemd.enable = true;
        args = [
          "-skip_launcher"
        ];

        files.game.place = {
          # ZHMModSDK
          "Retail".source = pkgs.fetchzip {
            url = "https://github.com/OrfeasZ/ZHMModSDK/releases/download/v4.1.0/ZHMModSDK-Release.zip";
            hash = "sha256-iyzvMyANB0du5Vp+P5QdFGRsNHtHcs9Rja+QT4ub4VM=";
            stripRoot = false;
          };

          # SMF (Simple Mod Framework)
          "Simple Mod Framework" = {
            source = pkgs.fetchzip {
              url = "https://github.com/atampy25/simple-mod-framework/releases/download/2.33.42/Release.zip";
              hash = "sha256-xLPKQ5RCv07K8i+7Gje7P04qfSNaOY+kOw0NEeiH+sE=";
              stripRoot = false;
            };
            mode = "seed"; # smf modifies itself during deployment
          };
          "Simple Mod Framework/config.json".source = "${inputs.mods}/hitman_woa/config.json";
          "Simple Mod Framework/Mods".source = "${inputs.mods}/hitman_woa/Mods";

          # Freelancer Variations prerequisites
          "Retail/mods/missioncompanion.ini" = {
            source = iniFormat.generate "missioncompanion" {
              general = {
                # This is the most important setting. Without it, freelancer variations does not work. All other settings seem to just be auto generated
                override_last_deploy_path = lastDeployJsonPath;
                allow_update_checks = true;
              };

              overrides = {
                force_load_teamruddcy_randomtods = false;
                force_load_kevinrudd_freelancervariations = false;
                force_load_teamruddcy_realyacht = false;
                force_load_kevinrudd_sandboxvector = false;
                force_load_kevinrudd_welcometocuba = false;
              };

              freelancervariations.dynamic_location_names = true;
            };
            mode = "lock";
          };
          "Retail/mods/FreelancerVariations.json" = {
            source = ./files/FreelancerVariations.json; # Generated from this site: https://www.piepieonline.com/h3-freelancer-variations-configuration
            mode = "lock";
          };
          "Retail/mods/MissionCompanion.dll".source = "${inputs.mods}/hitman_woa/MissionCompanion.dll";
        };
      };

      # To get smf working on linux: https://www.reddit.com/r/linux_gaming/comments/1aiiaia/how_to_run_simple_mod_framework_for_hitman_3_on/
      nonSteamApps."Simple Mod Framework (HITMAN WOA)" = {
        target = "${steamPath}/common/HITMAN 3/Simple Mod Framework/Mod Manager/Mod Manager.exe";
        startIn = config.programs.steam.config.apps."1659040".prefixPath;
        compatTool = "proton_experimental"; # Needs proton experimental to even start
        allowOverlay = false;
      };
    };

    custom.backup.backupPaths = lib.mkIf backup.enable [
      # Peacock save data
      "${peacockDir}/userdata"
    ];

    home-manager.users.dastarruer = {
      systemd.user.tmpfiles.rules = [
        "d ${peacockDir} - - - - -"
      ];

      systemd.user.services.peacock = let
        hitmanTarget = config.programs.steam.config.apps."1659040".systemd.target.unitName;
      in {
        Unit = {
          Before = [hitmanTarget]; # Wait for peacock to start before opening hitman
          PartOf = [hitmanTarget];
        };
        Service = {
          WorkingDirectory = peacockDir;
          ExecStart = "${lib.getExe peacockScript}";
          Restart = "always";
          RestartSec = 3;
        };
        Install.WantedBy = [hitmanTarget];
      };
    };
  };
}
