# Configures simple mod framework, the modding framework for hitman woa. Also downloads smf mods
{...}: {
  flake.nixosModules.desktop_steam = {
    config,
    pkgs,
    ...
  }: let
    hmConfig = config.home-manager.users.dastarruer;
    steamPath = "${hmConfig.home.homeDirectory}/.local/share/Steam/steamapps";

    iniFormat = pkgs.formats.ini {};
    smfPrefix = "3086416570";

    smfZip = pkgs.fetchzip {
      url = "https://github.com/atampy25/simple-mod-framework/releases/download/2.33.42/Release.zip";
      hash = "sha256-Kv78ZQQ2itsZQorizswV5f7eVATe08ZNnmtKmYheuiY=";
      stripRoot = false;
    };

    # This is the path to the json file generated by smf after deploying mods. Since linux is so special and cool, mission companion cannot find this file in the place it usually is, so we have to manually set the path.
    # Also note the \ instead of / for paths because windows
    lastDeployJsonPath = ''Z:\home\dastarruer\.local\share\Steam\steamapps\compatdata\${smfPrefix}\pfx\drive_c\users\steamuser\AppData\Local\Simple Mod Framework\lastDeploy.json'';

    # lot of mods to be downloaded
    burnTheWitchHeritageUI = pkgs.fetchzip {
      url = "https://github.com/Burn-the-witch/Heritage-UI/releases/download/14.0.3/mod.framework.zip";
      hash = "sha256-Ivziq7cjxEBF8unDwYYhRbJwN6EW/GO/EFOEgl5j6nQ=";
      stripRoot = false;
    };
    charc0alMoreBloodMelee = pkgs.fetchzip {
      url = "https://github.com/charc0al/HM3_MBM/releases/download/2.4.0/mod.framework.zip";
      hash = "sha256-1ageEt/d6ilfsNtLQ+tjq8bWfvGhQf5SvwP7WYgQeDQ=";
      stripRoot = false;
    };
    charc0alNoHoldButtons = pkgs.fetchzip {
      url = "https://github.com/charc0al/HM3_NoHoldButtons/releases/download/1.3.0/mod.framework.zip";
      hash = "sha256-KBaLqHTzEgkj1OIqDKZbFea74C/NlYi2fj2TDbHxBpw=";
      stripRoot = false;
    };
    charc0alThrownItemAdjustments = pkgs.fetchzip {
      url = "https://github.com/charc0al/HM3_ThrownItemAdjustments/releases/download/1.10.0/mod.framework.zip";
      hash = "sha256-KBaLqHTzEgkj1OIqDKZbFea74C/NlYi2fj2TDbHxBpw=";
      stripRoot = false;
    };
    freelancerVariations = pkgs.fetchzip {
      url = "https://github.com/Kevin-Rudd/FV-Autoupdater/releases/download/1.13.0/Freelancer.Variations.1.13.0.zip";
      hash = "sha256-gPiQUeDJEjF2F+pA0iSHwNvXOowih/SYoIaCp23wtt0=";
      stripRoot = false;
    };
    glacierOrganisationCommunityPatches = pkgs.fetchzip {
      url = "https://github.com/glacier-modding/H3-Unofficial-Community-Patch/releases/download/1.162.0/mod.framework.zip";
      hash = "sha256-PBzOBLOLAt0G6v4hXLaVEeZKfzN24j2E3ZeDHZJBXYc=";
      stripRoot = false;
    };
    invalidEarpiecevoiecs = pkgs.fetchzip {
      url = "https://github.com/scrungofan/handler-dialogue/releases/download/1.5.1/mod.framework.zip";
      hash = "sha256-02ZfzwA+vJIjzPYRn89PQh98SVHZM1lqC3Tkw3M91fI=";
      stripRoot = false;
    };
    jojjeBayHarborButcher = pkgs.fetchzip {
      url = "https://github.com/JojjeE/h3-bayharbor/releases/download/1.1.1/mod.framework.zip";
      hash = "sha256-5KDbVKd1dIk4WDZwT2EckEBlSLtrGgOG828FO/TBHqw=";
      stripRoot = false;
    };
    minnowMoreFreelancerTargets = pkgs.fetchzip {
      url = "https://github.com/Ocean-Minnow/Minnow.MoreFreelancerTargets/releases/download/1.1.0/mod.framework.zip";
      hash = "sha256-iNBBnV8cPMzV2jdCCyToac0Ao/i1ei508Z2Grtu6ecU=";
      stripRoot = false;
    };
    musicalmushr00mLightingUltimate = pkgs.fetchzip {
      url = "https://github.com/team-mushroom/lighting-ultimate/releases/download/2.6.1/mod.framework.zip";
      hash = "sha256-/7BSZPqIhANY1R4WQU2KDVVBmVw82VjdiV1MZSzxQhk=";
      stripRoot = false;
    };
    notexSimpleHealthBar = pkgs.fetchzip {
      url = "https://github.com/NotexMods/h3-simple-health-bar/releases/download/1.11.0/mod.framework.zip";
      hash = "sha256-P7UK5JbaDhqNd3BnmmcYwp1FfCTPrfnQ5yY/L1PoXTA=";
      stripRoot = false;
    };
    roguelessFreelancer = pkgs.fetchzip {
      url = "https://github.com/WINNODD/Rogueless-Freelancer/releases/download/2.1.1/Rogueless-Freelancer.zip";
      hash = "sha256-Ea58201PFDv16IyCDNCHp1pqPJPb3Mn5zT5bCF36uIw=";
      stripRoot = false;
    };
  in {
    programs.steam.config = {
      # hitman
      apps."1659040".files.game.place = {
        "Simple Mod Framework" = {
          source = smfZip;
          mode = "seed"; # smf modifies itself during deployment
        };
        "Simple Mod Framework/config.json".source = ./files/smf_config.json;

        # le mods
        "Simple Mod Framework/Mods/BurnTheWitch.HeritageUI".source = burnTheWitchHeritageUI;
        "Simple Mod Framework/Mods/Char0al.MoreBloodMelee".source = charc0alMoreBloodMelee;
        "Simple Mod Framework/Mods/Char0al.NoHoldButtons".source = charc0alNoHoldButtons;
        "Simple Mod Framework/Mods/Char0al.ThrownItemAdjustments".source = charc0alThrownItemAdjustments;
        "Simple Mod Framework/Mods/Freelancer Variations".source = freelancerVariations;
        "Simple Mod Framework/Mods/GlacierOrganisation.CommunityPatches".source = glacierOrganisationCommunityPatches;
        "Simple Mod Framework/Mods/invalid.earpiecevoices".source = invalidEarpiecevoiecs;
        "Simple Mod Framework/Mods/Jojje.BayHarborButcher".source = jojjeBayHarborButcher;
        "Simple Mod Framework/Mods/Minnow.MoreFreelancerTargets".source = minnowMoreFreelancerTargets;
        "Simple Mod Framework/Mods/musicalmushr00m.LightingUltimate".source = musicalmushr00mLightingUltimate;
        "Simple Mod Framework/Mods/No door hacking".source = ./files/mods/no_door_hacking;
        "Simple Mod Framework/Mods/Notex.SimpleHealthBar".source = notexSimpleHealthBar;
        "Simple Mod Framework/Mods/Readable UI".source = ./files/mods/readable_ui;
        "Simple Mod Framework/Mods/Rogueless-Freelancer".source = roguelessFreelancer;
        "Simple Mod Framework/Mods/Selfie Mode".source = ./files/mods/selfie_mode;

        # Freelancer Variations prerequisites
        "Retail/mods/missioncompanion.ini" = {
          source = iniFormat.generate "missioncompanion" {
            general = {
              # This is the most important setting. Without it, freelancer variations does not work. All other settings seem to just be auto generated
              override_last_deploy_path = lastDeployJsonPath;
              allow_update_checks = true;
            };

            overrides = {
              force_load_teamruddcy_randomtods = false;
              force_load_kevinrudd_freelancervariations = false;
              force_load_teamruddcy_realyacht = false;
              force_load_kevinrudd_sandboxvector = false;
              force_load_kevinrudd_welcometocuba = false;
            };

            freelancervariations.dynamic_location_names = true;
          };
          mode = "lock";
        };
        "Retail/mods/FreelancerVariations.json" = {
          source = ./files/FreelancerVariations.json; # Generated from this site: https://www.piepieonline.com/h3-freelancer-variations-configuration
          mode = "lock";
        };
      };

      # To get smf working on linux: https://www.reddit.com/r/linux_gaming/comments/1aiiaia/how_to_run_simple_mod_framework_for_hitman_3_on/
      nonSteamApps."Simple Mod Framework (HITMAN WOA)" = {
        target = "${steamPath}/common/HITMAN 3/Simple Mod Framework/Mod Manager/Mod Manager.exe";
        startIn = config.programs.steam.config.apps."1659040".prefixPath;
        compatTool = "proton_experimental"; # Needs proton experimental to even start
        allowOverlay = false;
      };
    };
  };
}
