# Configures simple mod framework, the modding framework for hitman woa.
{inputs, ...}: {
  flake.nixosModules.desktop_steam = {
    config,
    pkgs,
    ...
  }: let
    hmConfig = config.home-manager.users.dastarruer;
    steamPath = "${hmConfig.home.homeDirectory}/.local/share/Steam/steamapps";

    iniFormat = pkgs.formats.ini {};
    smfPrefix = "3086416570";

    smfZip = pkgs.fetchzip {
      url = "https://github.com/atampy25/simple-mod-framework/releases/download/2.33.42/Release.zip";
      hash = "sha256-Kv78ZQQ2itsZQorizswV5f7eVATe08ZNnmtKmYheuiY=";
      stripRoot = false;
    };

    # This is the path to the json file generated by smf after deploying mods. Since linux is so special and cool, mission companion cannot find this file in the place it usually is, so we have to manually set the path.
    # Also note the \ instead of / for paths because windows
    lastDeployJsonPath = ''Z:\home\dastarruer\.local\share\Steam\steamapps\compatdata\${smfPrefix}\pfx\drive_c\users\steamuser\AppData\Local\Simple Mod Framework\lastDeploy.json'';
  in {
    programs.steam.config = {
      # hitman
      apps."1659040".files.game.place = {
        "Simple Mod Framework" = {
          source = smfZip;
          mode = "seed"; # smf modifies itself during deployment
        };
        "Simple Mod Framework/config.json".source = ./files/smf_config.json;
        "Simple Mod Framework/Mods".source = "${inputs.mods}/hitman_woa/Mods";

        # Freelancer Variations prerequisites
        "Retail/mods/missioncompanion.ini" = {
          source = iniFormat.generate "missioncompanion" {
            general = {
              # This is the most important setting. Without it, freelancer variations does not work. All other settings seem to just be auto generated
              override_last_deploy_path = lastDeployJsonPath;
              allow_update_checks = true;
            };

            overrides = {
              force_load_teamruddcy_randomtods = false;
              force_load_kevinrudd_freelancervariations = false;
              force_load_teamruddcy_realyacht = false;
              force_load_kevinrudd_sandboxvector = false;
              force_load_kevinrudd_welcometocuba = false;
            };

            freelancervariations.dynamic_location_names = true;
          };
          mode = "lock";
        };
        "Retail/mods/FreelancerVariations.json" = {
          source = ./files/FreelancerVariations.json; # Generated from this site: https://www.piepieonline.com/h3-freelancer-variations-configuration
          mode = "lock";
        };
      };

      # To get smf working on linux: https://www.reddit.com/r/linux_gaming/comments/1aiiaia/how_to_run_simple_mod_framework_for_hitman_3_on/
      nonSteamApps."Simple Mod Framework (HITMAN WOA)" = {
        target = "${steamPath}/common/HITMAN 3/Simple Mod Framework/Mod Manager/Mod Manager.exe";
        startIn = config.programs.steam.config.apps."1659040".prefixPath;
        compatTool = "proton_experimental"; # Needs proton experimental to even start
        allowOverlay = false;
      };
    };
  };
}
